/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ritzau.test

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlinx.coroutines.launch
import kotlinx.coroutines.test.advanceUntilIdle
import kotlinx.coroutines.test.runTest

class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }

    @Test fun korut() = runTest {
        println("baz")
        launch {
            println("foo")
        }
        advanceUntilIdle()

        println("bar")
    }
}
