/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ritzau.test

import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.launch

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

suspend fun main(): Unit = coroutineScope {
    println("foo")
    launch {
        println(App().greeting)
    }
    println("bar")
}
